# Generated by Django 5.2.4 on 2025-12-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('story', 'Historia'), ('experience', 'Experiencia'), ('reflection', 'Reflexión')], default='null', max_length=20),
            preserve_default=False,
        ),
    ]
